# User configurations
users:
  - name: "developer_dave"
    groups:
      - "developer_dave"
  - name: "dan"
    groups:
      - "developer_dan"

# Group configurations
groups:
  - name: "developer_dave"
    description: "Developer_dave and his team"
  - name: "developer_dan"
    description: "Developer_dan and his team"

namespaces:
  - name: "developer-dave"
    operatorgroup: false
    bindings:
      - name: developer_dave
        kind: Group
        role: admin
    namespace: developer-dave
  - name: developer-dan
    operatorgroup: false
    bindings:
      - name: developer_dan
        kind: Group
        role: admin
    namespace: developer_dan
