---
apiVersion: v1
kind: Namespace
metadata:
  name: developer-dan
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: developer-dan
  annotations:
    description: Developer-dan and his team
users:
  - developer-dan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-dan
  namespace: developer-dan
subjects:
  - kind: Group
    name: developer-dan
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-dave-dan
  namespace: developer-dan
subjects:
  - kind: Group
    name: developer-dave
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: developer-dan
  namespace: developer-dan
spec:
  server:
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
    provider: dex
---
# apiVersion: argoproj.io/v1beta1
# kind: Application
# metadata:
#   name: bgd-app
#   namespace: developer-dan
# spec:
#   destination:
#     namespace: developer-dan
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     path: apps/bgd/overlays/bgd
#     repoURL: https://github.com/rhyspowell/developer-dan
#     targetRevision: main
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: false
