---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: developer-dan
  annotations:
    openshift.io/description: team developer dan
    openshift.io/display-name: developer-dan
  labels:
    kubernetes.io/metadata.name: developer-dan
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: developer-dan
  annotations:
    description: Developer-dan and his team
users:
  - developer-dan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-dan
  namespace: developer-dan
subjects:
  - kind: Group
    name: developer-dan
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-dan-dave
  namespace: developer-dave
subjects:
  - kind: Group
    name: developer-dan
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-dave-dan
  namespace: developer-dan
subjects:
  - kind: Group
    name: developer-dave
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: developer-dan
  namespace: developer-dan
spec:
  server:
    route:
      enabled: true
      path: /
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: passthrough
      wildcardPolicy: None
