---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: developer-dave
  annotations:
    openshift.io/description: team developer dave
    openshift.io/display-name: developer-dave
  labels:
    kubernetes.io/metadata.name: developer-dave
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: secret-takeover-the-world
  annotations:
    openshift.io/description: ssshhhhhhh
    openshift.io/display-name: shhhhhhh
  labels:
    kubernetes.io/metadata.name: shhhh
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: developer-dave
  annotations:
    description: Developer-dave and his team
users:
  - developer-dave
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-dave
  namespace: developer-dave
subjects:
  - kind: Group
    name: developer-dave
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-takeover-the-world
  namespace: secret-takeover-the-world
subjects:
  - kind: Group
    name: developer-dave
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: developer-dave
  namespace: developer-dave
spec:
  server:
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
  # sso:
  #   dex:
  #     openShiftOAuth: true
  #     resources:
  #       limits:
  #         cpu: 500m
  #         memory: 256Mi
  #       requests:
  #         cpu: 250m
  #         memory: 128Mi
  #   provider: dex
---
apiVersion: argoproj.io/v1beta1
kind: Application
metadata:
  name: bgd-app
  namespace: developer-dave
spec:
  destination:
    namespace: bgd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/bgd/overlays/bgd
    repoURL: https://github.com/rhyspowell/developer-dave
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
